In [2]:
import numpy as np
from sklearn.linear_model import Perceptron
import pandas as pd    #importing librabies needed
from sklearn.metrics import confusion_matrix, classification_report



In [4]:
#class Perceprton: 
    #def _init (self, learning_rate=0.01, n_iter=1000):
     #   self.lr = learning_rate
      #  self.n_iter = n_iter 
       # self.activation_func = self.unit_step_func
        #self.weights = None 
        #self.bias = None 

In [5]:
#def fit(self, x):
 #   pass

In [6]:
#def unit_step_func(self,x):
 #   return np.where(x>=0,1,0)

In [4]:
#def predict(self,x):
 #   linear_output= np.dot(x, self.weights) + self.bias 
  #  y_oredicted = self.activation_func(linear_output)
   # return y_predicted 

    

In [3]:
per = Perceptron()

In [4]:
file = pd.read_csv('train_1.csv')        #reading the training file 

In [5]:
y_train = file.iloc[:,-1:]               #splitting the last column from the training set (the result)


In [6]:
x_train = file.iloc[:,:-1]               #splitting features columns 


In [8]:
per.fit(x_train, y_train.values.ravel())


Perceptron()

In [9]:
test = pd.read_csv('test_with_label_1.csv')    #reading the test file

In [10]:
x_test = test.iloc[:,:-1]             #splitting features columns 

In [11]:
y_test = test.iloc[:,-1:]             #splitting the last column from the test set (the result)

In [12]:
per_pred = per.predict(x_test)
per_pred

array([13, 22,  2, 18, 17, 18, 23, 22, 20,  2,  9, 11, 24,  4,  5,  6,  8,
        2, 12, 16,  0, 25, 17,  9,  1, 21,  8, 23,  8,  3, 23, 10, 16, 10,
       23,  6, 19, 15,  3, 16, 11, 13,  1, 13,  7, 10, 14, 24,  0,  7,  3,
       22, 20,  3, 14, 25,  9, 17, 14,  7,  2, 11,  7, 22,  6,  6, 20, 12,
        1, 24, 22, 21,  8, 22, 18, 15, 17,  6, 19], dtype=int64)

In [13]:
print(classification_report(y_test,per_pred))   #generating the report 

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         4
           1       0.67      1.00      0.80         2
           2       1.00      1.00      1.00         4
           3       0.75      1.00      0.86         3
           4       1.00      1.00      1.00         1
           5       1.00      0.50      0.67         2
           6       0.80      1.00      0.89         4
           7       0.50      0.67      0.57         3
           8       0.75      1.00      0.86         3
           9       1.00      0.75      0.86         4
          10       0.33      0.33      0.33         3
          11       1.00      0.75      0.86         4
          12       0.50      0.33      0.40         3
          13       1.00      0.75      0.86         4
          14       1.00      1.00      1.00         3
          15       1.00      0.67      0.80         3
          16       1.00      1.00      1.00         3
          17       0.75    

In [14]:
conf_matrix= (confusion_matrix(y_test,per_pred)) 

In [15]:
print(confusion_matrix(y_test,per_pred))    #generating the confusion matrix

[[2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 0 0 0 